stages:
- greeting
#- build
- run

hello:
  stage: greeting
  script:
   - echo "Hey there! Let's prepare some tamales."

#build_image:
#  stage: build
#  variables:
#    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
#  tags:
#    - docker-image-build
#  script:
#    - ignore

make_test:
  stage: run
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script:
    - source setup.sh
    - source /media/data_hdd/Xilinx/Vivado/2021.1/settings64.sh
    - source tests/startup.sh -i 210308B0B4F5 -k 192.168.0.12 -p 192.168.2.3:ch2
    - source tests/software_emulator.sh
