stages:
- greeting
- build
- run

hello:
  stage: greeting
  script:
   - echo "Hey there! Let's prepare some tamales."

build_image:
  stage: build
  variables:
    TO: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  tags:
    - docker-image-build
  script:
    - ignore

make_test:
  stage: run
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  script:
    - source setup.sh
    - python3 tests/unit_test.py
