emulator_adapter:
   clocks:
      - 3
      - 4
      - 5
      - 22
      - 23
      - 25
      - 26
      - 27
   downlink:   # Downlink registers follow the AB = 4A + B system (e.g. 10 = 4*1 + 0 = 4)
      - 02     # -> 2
      - 10     # -> 4
      - 20     # -> 8
      - 22     # -> 10
      - 30     # -> 12
   uplink:
      - 6
      - 12
      - 14
      - 16
      - 18
      - 20
      - 22
   trigger:
      - 2
      - 6
      - 10
      - 16
      - 18
      - 20
      - 22
