base:
  # FIXME physical addresses are based on v1 (please double check)
  v0:
    # [0x020] CLKGConfig0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCALIBRATIONENDOFCOUNT": 0xF  # default from ME0 is 0xC
    "LPGBT.RWF.CLOCKGENERATOR.CLKGBIASGENCONFIG": 0x8

    # [0x021] CLKGConfig1
    "LPGBT.RWF.CLOCKGENERATOR.CDRCONTROLOVERRIDEENABLE": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGDISABLEFRAMEALIGNERLOCKCONTROL": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRRES": 0x1
    "LPGBT.RWF.CLOCKGENERATOR.CLKGVCODAC": 0x4  # 0x8
    "LPGBT.RWF.CLOCKGENERATOR.CLKGVCORAILMODE": 0x0  # 0x1

    # [0x022] CLKGPllRes
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLRESWHENLOCKED": 0x4
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLRES": 0x4

    #[0x023] CLKGPLLIntCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLINTCURWHENLOCKED": 0x5
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLINTCUR": 0x5

    #[0x024] CLKGPLLPropCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLPROPCURWHENLOCKED": 0x5
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLPROPCUR": 0x5

    #[0x025] CLKGCDRPropCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRPROPCURWHENLOCKED": 0x5
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRPROPCUR": 0x5

    #[0x026] CLKGCDRIntCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRINTCURWHENLOCKED": 0x5
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRINTCUR": 0x5

    #[0x027] CLKGCDRFFPropCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRFEEDFORWARDPROPCURWHENLOCKED": 0x5
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRFEEDFORWARDPROPCUR": 0x5

    #[0x028] CLKGFLLIntCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFLLINTCURWHENLOCKED": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFLLINTCUR": 0xF  #0x5

    #[0x029] CLKGFFCAP
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOCONNECTCDR": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKOVERRIDEENABLE": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFEEDFORWARDCAPWHENLOCKED": 0x6  # 0x3
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFEEDFORWARDCAP": 0x6  # 0x3

    #[0x02a] CLKGCntOverride
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCOOVERRIDEVC": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOREFCLKSEL": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLEPLL": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLEFD": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLECDR": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCODISDATACOUNTERREF": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCODISDESVBIASGEN": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOCONNECTPLL": 0x0

    #[0x02b] CLKGOverrideCapBank
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKSELECT_7TO0": 0x00

    #[0x02c] CLKGWaitTime
    "LPGBT.RWF.CLOCKGENERATOR.CLKGWAITCDRTIME": 0xA  # 0x8
    "LPGBT.RWF.CLOCKGENERATOR.CLKGWAITPLLTIME": 0x0  # 0x8

    #[0x02d] CLKGLFCONFIG0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERLOCKTHRCOUNTER": 0x9
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERENABLE": 0x1
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKSELECT_8": 0x0

    #[0x02e] CLKGLFConfig1
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERRELOCKTHRCOUNTER": 0x9
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERUNLOCKTHRCOUNTER": 0x9

    #[0x033] PSDllConfig
    "LPGBT.RWF.CLOCKGENERATOR.PSDLLCONFIRMCOUNT": 0x2  # 0x1 # 4 40mhz clock cycles to confirm lock
    "LPGBT.RWF.CLOCKGENERATOR.PSDLLCURRENTSEL": 0x2  # 0x1

    #[0x039] Set H.S. Uplink Driver current:
    "LPGBT.RWF.LINE_DRIVER.LDMODULATIONCURRENT": 0x40  # 0x20
    "LPGBT.RWF.LINE_DRIVER.LDEMPHASISENABLE": 0x0

    # [0x03b] REFCLK
    "LPGBT.RWF.LINE_DRIVER.REFCLKACBIAS": 0x1  # this was commented out
    "LPGBT.RWF.LINE_DRIVER.REFCLKTERM": 0x1  # FIXME this was in

    #[0x03E] PGCONFIG
    "LPGBT.RWF.POWER_GOOD.PGLEVEL": 0x0  # 0x5
    "LPGBT.RWF.POWER_GOOD.PGENABLE": 0x1
    "LPGBT.RWF.POWER_GOOD.PGDELAY": 0xC

    "LPGBT.RWF.CALIBRATION.EPRXLOCKTHRESHOLD": 0x0  # 0x5
    "LPGBT.RWF.CALIBRATION.EPRXRELOCKTHRESHOLD": 0x0  # 0x5
    "LPGBT.RWF.CLOCKGENERATOR.EPRXUNLOCKTHRESHOLD": 0x0  # 0x5

    # Datapath configuration
    "LPGBT.RW.DEBUG.DLDPBYPASDEINTERLEVEAR": 0x0
    "LPGBT.RW.DEBUG.DLDPBYPASFECDECODER": 0x0
    "LPGBT.RW.DEBUG.DLDPBYPASSDESCRAMBLER": 0x0
    "LPGBT.RW.DEBUG.DLDPFECERRCNTENA": 0x0  # 0x1
    "LPGBT.RW.DEBUG.ULDPBYPASSINTERLEAVER": 0x0
    "LPGBT.RW.DEBUG.ULDPBYPASSSCRAMBLER": 0x0
    "LPGBT.RW.DEBUG.ULDPBYPASSFECCODER": 0x0

    "LPGBT.RWF.POWERUP.DLLCONFIGDONE": 0x1
    "LPGBT.RWF.POWERUP.PLLCONFIGDONE": 0x1

  v1:
    # [0x020] CLKGConfig0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCALIBRATIONENDOFCOUNT": 0xE
    "LPGBT.RWF.CLOCKGENERATOR.CLKGBIASGENCONFIG": 0x8

    # [0x021] CLKGConfig1
    "LPGBT.RWF.CLOCKGENERATOR.CDRCONTROLOVERRIDEENABLE": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGDISABLEFRAMEALIGNERLOCKCONTROL": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRRES": 0x1
    "LPGBT.RWF.CLOCKGENERATOR.CLKGVCODAC": 0x8
    "LPGBT.RWF.CLOCKGENERATOR.CLKGVCORAILMODE": 0x1

    # [0x022] CLKGPllRes
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLRESWHENLOCKED": 0x2
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLRES": 0x2

    #[0x023] CLKGPLLIntCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLINTCURWHENLOCKED": 0x9
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLINTCUR": 0x9

    #[0x024] CLKGPLLPropCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLPROPCURWHENLOCKED": 0x9
    "LPGBT.RWF.CLOCKGENERATOR.CLKGPLLPROPCUR": 0x9

    #[0x025] CLKGCDRPropCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRPROPCURWHENLOCKED": 0x5
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRPROPCUR": 0x5

    #[0x026] CLKGCDRIntCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRINTCURWHENLOCKED": 0x5
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRINTCUR": 0x5

    #[0x027] CLKGCDRFFPropCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRFEEDFORWARDPROPCURWHENLOCKED": 0x6
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCDRFEEDFORWARDPROPCUR": 0x6

    #[0x028] CLKGFLLIntCur
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFLLINTCURWHENLOCKED": 0x5
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFLLINTCUR": 0x5

    #[0x029] CLKGFFCAP
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOCONNECTCDR": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKOVERRIDEENABLE": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFEEDFORWARDCAPWHENLOCKED": 0x3
    "LPGBT.RWF.CLOCKGENERATOR.CLKGFEEDFORWARDCAP": 0x3

    #[0x02a] CLKGCntOverride
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCOOVERRIDEVC": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOREFCLKSEL": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLEPLL": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLEFD": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOENABLECDR": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCODISDATACOUNTERREF": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCODISDESVBIASGEN": 0x0
    "LPGBT.RWF.CLOCKGENERATOR.CDRCOCONNECTPLL": 0x0

    #[0x02b] CLKGOverrideCapBank
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKSELECT_7TO0": 0x00

    #[0x02c] CLKGWaitTime
    "LPGBT.RWF.CLOCKGENERATOR.CLKGWAITCDRTIME": 0x8
    "LPGBT.RWF.CLOCKGENERATOR.CLKGWAITPLLTIME": 0x8

    #[0x02d] CLKGLFCONFIG0
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERLOCKTHRCOUNTER": 0xF
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERENABLE": 0x1
    "LPGBT.RWF.CLOCKGENERATOR.CLKGCAPBANKSELECT_8": 0x0

    #[0x02e] CLKGLFConfig1
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERRELOCKTHRCOUNTER": 0xF
    "LPGBT.RWF.CLOCKGENERATOR.CLKGLOCKFILTERUNLOCKTHRCOUNTER": 0xF

    #[0x033] PSDllConfig
    "LPGBT.RWF.CLOCKGENERATOR.PSDLLCONFIRMCOUNT": 0x1 # 4 40mhz clock cycles to confirm lock
    "LPGBT.RWF.CLOCKGENERATOR.PSDLLCURRENTSEL": 0x1

    #[0x039] Set H.S. Uplink Driver current:
    "LPGBT.RWF.LINE_DRIVER.LDMODULATIONCURRENT": 0x7F
    "LPGBT.RWF.LINE_DRIVER.LDEMPHASISENABLE": 0x0

    # [0x03b] REFCLK
    "LPGBT.RWF.LINE_DRIVER.REFCLKACBIAS": 0x1
    "LPGBT.RWF.LINE_DRIVER.REFCLKTERM": 0x1  # FIXME this was in

    #[0x03E] PGCONFIG
    "LPGBT.RWF.POWER_GOOD.PGLEVEL": 0x4
    "LPGBT.RWF.POWER_GOOD.PGENABLE": 0x1
    "LPGBT.RWF.POWER_GOOD.PGDELAY": 0xC

    "LPGBT.RWF.EPORTRX.EPRXLOCKTHRESHOLD": 0x5
    "LPGBT.RWF.EPORTRX.EPRXRELOCKTHRESHOLD": 0x5
    "LPGBT.RWF.EPORTRX.EPRXUNLOCKTHRESHOLD": 0x5

    # Datapath configuration
    "LPGBT.RW.DEBUG.DLDPBYPASDEINTERLEVEAR": 0x0
    "LPGBT.RW.DEBUG.DLDPBYPASFECDECODER": 0x0
    "LPGBT.RW.DEBUG.DLDPBYPASSDESCRAMBLER": 0x0
    "LPGBT.RW.DEBUG.DLDPFECCOUNTERENABLE": 0x1
    "LPGBT.RW.DEBUG.ULDPBYPASSINTERLEAVER": 0x0
    "LPGBT.RW.DEBUG.ULDPBYPASSSCRAMBLER": 0x0
    "LPGBT.RW.DEBUG.ULDPBYPASSFECCODER": 0x0

    "LPGBT.RWF.POWERUP.DLLCONFIGDONE": 0x1
    "LPGBT.RWF.POWERUP.PLLCONFIGDONE": 0x1

ec:
  v0:
    "LPGBT.RWF.EPORTRX.EPRXECTERM": 1
    "LPGBT.RWF.EPORTRX.EPRXECENABLE": 1
    "LPGBT.RWF.EPORTRX.EPRXECACBIAS": 0
    "LPGBT.RWF.EPORTRX.EPRXECINVERT": 1
    "LPGBT.RWF.EPORTRX.EPRXECPHASESELECT": 8
    "LPGBT.RWF.EPORTRX.EPRXECTRACKMODE": 2  # 0x2 = continuous tracking

    "LPGBT.RWF.EPORTTX.EPTXECINVERT": 1
    "LPGBT.RWF.EPORTTX.EPTXECENABLE": 1
    "LPGBT.RWF.EPORTTX.EPTXECDRIVESTRENGTH": 4

    "LPGBT.RWF.EPORTCLK.EPCLK28FREQ": 1  # 1 =  40mhz
    "LPGBT.RWF.EPORTCLK.EPCLK28INVERT": 1
    "LPGBT.RWF.EPORTCLK.EPCLK28DRIVESTRENGTH": 4
  v1:
    "LPGBT.RWF.EPORTRX.EPRXECTERM": 1
    "LPGBT.RWF.EPORTRX.EPRXECENABLE": 1
    "LPGBT.RWF.EPORTRX.EPRXECACBIAS": 0
    "LPGBT.RWF.EPORTRX.EPRXECINVERT": 1
    "LPGBT.RWF.EPORTRX.EPRXECPHASESELECT": 8
    "LPGBT.RWF.EPORTRX.EPRXECTRACKMODE": 0  # confirmed, https://lpgbt.web.cern.ch/lpgbt/v1/registermap.html, 0x0 = continuous tracking in v1

    "LPGBT.RWF.EPORTTX.EPTXECINVERT": 1
    "LPGBT.RWF.EPORTTX.EPTXECENABLE": 1
    "LPGBT.RWF.EPORTTX.EPTXECDRIVESTRENGTH": 4

    "LPGBT.RWF.EPORTCLK.EPCLK28FREQ": 1  # 1 =  40mhz
    "LPGBT.RWF.EPORTCLK.EPCLK28INVERT": 1
    "LPGBT.RWF.EPORTCLK.EPCLK28DRIVESTRENGTH": 4
