adc:
    1V2_mon0:
        pin: 0x01
        conv: 1
        flavor: small
        comment: monitoring for 1.2V of ETROC0
    1V2_mon1:
        pin: 0x03
        conv: 1
        flavor: small
        comment: monitoring for 1.2V of ETROC1
    1V2_mon2:
        pin: 0x06
        conv: 1
        flavor: small
        comment: monitoring for 1.2V of ETROC2
    1V2_mon3:
        pin: 0x09
        conv: 1
        flavor: small
        comment: monitoring for 1.2V of ETROC3
    1V2_mon4:
        pin: 0x0C
        conv: 1
        flavor: small
        comment: monitoring for 1.2V of ETROC4
    1V2_mon5:
        pin: 0x0F
        conv: 1
        flavor: small
        comment: monitoring for 1.2V of ETROC5
    1V2_mon6:
        pin: 0x01
        conv: 1
        flavor: medium
    BV0:
        pin: 0x12
        conv: 1220
        flavor: small
        comment: monitoring for BV line 0
    BV1:
        pin: 0x15
        conv: 1220
        flavor: small
        comment: monitoring for BV line 1
    BV2:
        pin: 0x1C
        conv: 1220
        flavor: small
        comment: monitoring for BV line 2
    1V2A:
        pin: 0x17
        conv: 2.5
        flavor: small
        comment: 1.2v reference voltage A        
    1V2B:
        pin: 0x18
        conv: 2.5
        flavor: small
        comment: 1.2v reference voltage B        
    1V2C:
        pin: 0x19
        conv: 2.5
        flavor: small
        comment: 1.2v reference voltage C        
    1V2D:
        pin: 0x16
        conv: 2.5
        flavor: small
        comment: 1.2v reference voltage D        
    LV_RB:
        pin: 0x1E
        conv: 2.5
        flavor: small
        comment: low voltage (?)        

        
gpio: None



