0:
    type: "modulev1"
    psu: [["192.168.2.1", "ch1"], ["192.168.2.1", "ch2"]]
    modules: [[104], [], []]
1:
    type: "modulev0b"
    psu: [["192.168.2.2", "ch1"]]
    modules: [[20], [], []]
2:
    type: "modulev0b"
    psu: [["192.168.2.2", "ch2"]]
    modules: [[12],  [], []]
